version: '3.9'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app_container
    # ports:
    #   - "7860:7860"
    # environment:
    #   - PYTHONUNBUFFERED=1
    #   - ENV_FILE=./.env  # If you use an environment file
    platform: linux/amd64
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]
